---

- name: deploy istlukasschonwach.de
  hosts: oracle
  remote_user: svenstaro
  become: yes
  become_user: root
  vars:
    site_url: istlukasschonwach.de
    site_path: /srv/ilswlol
  tasks:
  - set_fact: envvars="{{ lookup('file', '../secrets') }}"

  - name: pull git repo
    register: gitstatus
    git: accept_hostkey=yes
         force=yes
         recursive=yes
         repo=git://github.com/svenstaro/ilswlol.git
         dest={{ site_path }}

  - name: create nginx log directory
    file: owner=http group=log mode=750 state=directory path=/var/log/nginx/{{ site_url }}

  - name: create app dir
    file: owner=http group=http mode=750 state=directory path={{ site_url }}

  - name: configure uwsgi
    template: src=ilswlol_uwsgi.ini.j2 dest=/etc/uwsgi/{{ site_url }}.ini owner=root group=http mode=640
    notify:
      - restart uwsgi

  - name: configure nginx
    template: src=ilswlol_nginx.conf.j2 dest=/etc/nginx/vhosts/{{ site_url }}.conf owner=root group=root mode=644
    notify:
      - restart nginx

  - name: reload nginx
    service: name=nginx state=reloaded enabled=yes

  - name: start uwsgi
    service: name=uwsgi@{{ site_url }} state=reloaded enabled=yes

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
    - name: restart uwsgi
      service: name=uwsgi@{{ site_url }} state=restarted
